import XCTest
import Foundation

/// THE SHIPPED-DOC DRIFT GATE, in `swift test`.
///
/// `AGENTS.md` is the canonical agent contract; `Sources/candor-swift/AgentsDoc.swift` embeds it as a
/// string constant (generated by `gen-agents-doc.py`) so `--agents` works from a binary copied out of
/// `.build`, where `Bundle.module` would `fatalError`. Two copies of one document.
///
/// `smoke.sh` diffs them — but only end to end, only when a release binary has been built, and only
/// when someone runs it. Nothing in `Tests/` tied the two together, and at the 0.23→0.24 floor bump
/// they diverged inside a single file: `AgentsDoc.swift` was hand-edited to say spec 0.24 at one line
/// while still saying 0.23 at another, and `AGENTS.md` said 0.23 at both. The engine PRINTED a document
/// that contradicted itself, and every gate stayed green.
///
/// These tests are FILE-BASED on purpose — no built binary, no `XCTSkipUnless`, so they cannot pass by
/// being skipped on a machine that has not run `swift build`.
final class AgentsDocDriftTests: XCTestCase {

    private static let repoRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()

    private static func read(_ relative: String) throws -> String {
        let url = repoRoot.appendingPathComponent(relative)
        return try String(contentsOf: url, encoding: .utf8)
    }

    /// The spec contract the BINARY declares — the one value everything else must agree with. Read from
    /// the source constant rather than written here as a literal: a literal in a drift test is the exact
    /// failure this file exists to prevent (candor-java's docs gate asserted `spec 0.23` and so pinned
    /// the drift it was meant to catch).
    private func declaredSpec() throws -> String {
        let src = try Self.read("Sources/candor-swift/main.swift")
        let m = try XCTUnwrap(
            src.firstMatch(of: /let\s+specVersion\s*=\s*"([0-9]+\.[0-9]+)"/),
            "no `let specVersion = \"X.Y\"` in Sources/candor-swift/main.swift — the constant moved or was renamed; this gate reads it by name and must be updated with it")
        return String(m.1)
    }

    /// THE FLOOR, as a LITERAL, and deliberately so.
    ///
    /// Everything else in this repo derives the spec from `specVersion` — the drift gates, smoke.sh's
    /// `BSPEC`, and `GateProcessTests`' verdict assertion — which is right for checking AGREEMENT and
    /// useless for checking the VALUE. After those derivations landed there was no in-tree pin at all:
    /// setting `specVersion = "0.29"` passed every candor-swift test and both drift gates. This is the
    /// canary that notices the constant moved, so it must stay a literal; deriving it makes it vacuous.
    /// candor-report's `assert_eq!(SPEC_VERSION, "0.29")` is the same fixture in the rust arm.
    func testTheDeclaredFloorIsThePinnedOne() throws {
        XCTAssertEqual(try declaredSpec(), "0.35",
                       "the spec floor moved — bump this pin with it, deliberately, as part of the rung")
    }

    // ── 1. the two copies are the SAME DOCUMENT ─────────────────────────────────────────────────────

    /// Asserts the SHARED CONTENT, not just the spec string. The spec string is one symptom; the defect
    /// is that a generated file can be edited in place and nothing notices. Byte equality catches every
    /// hand-edit, including the ones nobody thought to write an assertion for.
    func testEmbeddedContractIsByteIdenticalToAgentsMd() throws {
        let canonical = try Self.read("AGENTS.md")
        let generated = try Self.read("Sources/candor-swift/AgentsDoc.swift")

        // Assembled, not written as a literal: the delimiters are themselves quote runs, and a raw
        // string spelling them out collides with Swift's own `#` counting.
        let q3 = "\u{22}\u{22}\u{22}"
        let open = "let AGENTS_MD = #####" + q3 + "\n"
        let close = "\n" + q3 + "#####"
        let start = try XCTUnwrap(generated.range(of: open),
                                  "AgentsDoc.swift no longer opens with the generated raw-string header — regenerate: python3 gen-agents-doc.py")
        let end = try XCTUnwrap(generated.range(of: close, options: .backwards),
                                "AgentsDoc.swift no longer closes the generated raw string — regenerate: python3 gen-agents-doc.py")
        // The generator writes `…{doc}"""#####`, and the doc ends in a newline, so the closing delimiter
        // is preceded by that newline — restore it when slicing back out.
        let embedded = String(generated[start.upperBound..<end.lowerBound]) + "\n"

        XCTAssertEqual(embedded, canonical, """
            Sources/candor-swift/AgentsDoc.swift has drifted from AGENTS.md — the doc the engine PRINTS \
            is not the doc in the repo. AGENTS.md is canonical; regenerate: python3 gen-agents-doc.py
            """)
    }

    // ── 2. every CURRENT-CONTRACT spec claim matches the binary ─────────────────────────────────────

    /// A `spec <X>` claim in prose is a claim about the contract this build speaks — EXCEPT when it is a
    /// historical marker naming the rung a feature arrived at, which is written `(spec 0.23, informative)`
    /// and must NOT move when the floor does. The exemption keys on that marker rather than on a list of
    /// allowed old versions: it encodes the actual distinction, and it does not need editing every time a
    /// legitimate annotation is added.
    ///
    /// The equality gate above cannot catch this class — a COHERENT stale pair (both copies saying 0.23
    /// under a 0.24 binary) is byte-identical and passes.
    func testCurrentContractSpecClaimsMatchTheDeclaredSpec() throws {
        let spec = try declaredSpec()
        // THE FAMILY'S SHARED CLAIM GRAMMAR: `spec`, then one to EIGHT of `[-: "*)\]]`, then
        // `<digits>.<digits>` — so `spec §6.1` (a SECTION reference) and `SPEC §2.2` never look like
        // versions, while `spec 0.24`, `spec-0.24`, `"spec": "0.24"`, the ALIGNED `"spec":    "0.24"`
        // and the markdown-link `[candor-spec](…) 0.24` are all covered.
        //
        // THE LAST TWO ARE THE ⟨0.32⟩ WIDENING and one of them was live in THIS repo: README.md line 3
        // reads `**The Swift implementation of [candor-spec](…) 0.32**`, and the `) ` between the word
        // and the version put it outside a `{1,4}` grammar. This gate is the one the other four engines
        // ported BECAUSE it was clean through the ⟨0.32⟩ bump — and it was clean over its own README's
        // headline claim, which it could not see. A gate cited as the reason a spelling is covered has
        // to be asked which spellings it actually reads.
        let claim = /spec[-: "*)\]]{1,8}([0-9]+\.[0-9]+)/

        for doc in ["AGENTS.md", "README.md", "SPEC-EXTENSION-privacy.md"] {
            let text = try Self.read(doc)
            for m in text.matches(of: claim) {
                let version = String(m.1)
                let tail = text[m.range.upperBound...].prefix(16)
                if tail.hasPrefix(", informative)") { continue }   // historical marker — pinned on purpose
                XCTAssertEqual(version, spec, """
                    \(doc) claims spec \(version) but this build declares spec \(spec) — at "\
                    \(text[m.range])\(tail)". If that is a historical marker naming the rung a feature \
                    arrived at, write it "(spec \(version), informative)"; otherwise bump it.
                    """)
            }
        }
    }

    /// The exemption must actually exempt, and must not exempt everything. Without this, a broken
    /// `, informative)` check would silently turn the gate above into a no-op.
    func testInformativeMarkerExemptionDiscriminates() throws {
        let claim = /spec[-: "*)\]]{1,8}([0-9]+\.[0-9]+)/
        // The same fixture the java/rust/ts/agents copies of this grammar carry, so a widening applied
        // in one engine and forgotten in another reddens rather than going quiet. The last two lines
        // are spellings a `{1,4}` grammar cannot reach at all.
        let sample = """
            carrying `unitKind: "accessor"` (spec 0.8, informative); ordinary
            This project is on candor-swift 9.9.9 (spec 0.9).
            a section reference, spec §6.1, is not a version
            the gate prints { "spec": "0.7", "ok": true }
            and the hyphenated attributive spec-0.6 form
            an aligned envelope column, { "spec":    "0.5" }
            a markdown link [candor-spec](https://example.org/candor-spec) 0.4
            """
        let flagged = sample.matches(of: claim).filter {
            !sample[$0.range.upperBound...].prefix(16).hasPrefix(", informative)")
        }.map { String($0.1) }
        XCTAssertEqual(flagged, ["0.9", "0.7", "0.6", "0.5", "0.4"],
                       "the exemption must skip the annotated claim, keep the live prose one, SEE the JSON, hyphenated, ALIGNED-JSON and MARKDOWN-LINK spellings, and never read `spec §6.1` as a version")
    }
}
